apiVersion: v1
kind: Namespace
metadata:
  name: toggle-master
---
# --- CONFIGMAP (Endereços e Configurações Não-Sensíveis) ---
apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: toggle-master
data:
  # Hosts RDS e Redis (Gerados dinamicamente via IaC AWS)
  auth-db-host: "${module.database.postgres_endpoints[0]}"
  flag-db-host: "${module.database.postgres_endpoints[1]}"
  targeting-db-host: "${module.database.postgres_endpoints[2]}"
  
  # --- CACHE ---
  REDIS_ADDR: "${module.database.redis_endpoint}"
  
  # Nomes dos Databases
  auth-db-name: "auth_db"
  flag-db-name: "flag_db"
  targeting-db-name: "targeting_db"

  # Configurações AWS Gerais
  sqs-url: "https://sqs.us-east-1.amazonaws.com/797561896734/analytics-service-sqs"
  dynamo-table: "ToggleMasterAnalytics"
  aws-region: "us-east-1"
  
  # Portas Padrão Internas
  db-port: "5432"
  db-user: "postgres"
  redis-port: "6379"

  # OpenTelemetry Collector Endpoints (namespace monitoring)
  otel-collector-grpc: "otel-collector-opentelemetry-collector.monitoring.svc.cluster.local:4317"
  otel-collector-http: "otel-collector-opentelemetry-collector.monitoring.svc.cluster.local:4318"
