apiVersion: v1
kind: ServiceAccount
metadata:
  name: togglemaster-sa
  namespace: toggle-master
  annotations:
    # OBS: O AWS IAM Account ID deve coincidir com o da sua console.
    eks.amazonaws.com/role-arn: arn:aws:iam::797561896734:role/LabRole
