apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: app-secrets-external
  namespace: toggle-master
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: aws-secrets-store
    kind: SecretStore
  target:
    name: app-secrets # The name of the native K8s Secret to be created by ESO
    creationPolicy: Owner
  data:
  - secretKey: db-password
    remoteRef:
      key: togglemaster/app-secrets
      property: db-password
  - secretKey: master-key
    remoteRef:
      key: togglemaster/app-secrets
      property: master-key
  - secretKey: service-api-key
    remoteRef:
      key: togglemaster/app-secrets
      property: service-api-key
  - secretKey: new-relic-license-key
    remoteRef:
      key: togglemaster/app-secrets
      property: new-relic-license-key
